// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5pedY0_buClWOkCpiLnEguw0aO77sfj4',
    appId: '1:195527179707:web:eebf74fa8f6f5be038189e',
    messagingSenderId: '195527179707',
    projectId: 'challenge-rickyflix',
    authDomain: 'challenge-rickyflix.firebaseapp.com',
    storageBucket: 'challenge-rickyflix.appspot.com',
    measurementId: 'G-CY39V4GTW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARN8rHc6wvWeRH6aHXN83Bl0akfT8gcXI',
    appId: '1:195527179707:android:e49c7cc5d475d32a38189e',
    messagingSenderId: '195527179707',
    projectId: 'challenge-rickyflix',
    storageBucket: 'challenge-rickyflix.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7t4Fq6LGfmhChD0ntz3KZatGCkSJnue0',
    appId: '1:195527179707:ios:51f58df3931c90ca38189e',
    messagingSenderId: '195527179707',
    projectId: 'challenge-rickyflix',
    storageBucket: 'challenge-rickyflix.appspot.com',
    iosBundleId: 'com.example.rickyflixChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7t4Fq6LGfmhChD0ntz3KZatGCkSJnue0',
    appId: '1:195527179707:ios:3a5360c40d113cd338189e',
    messagingSenderId: '195527179707',
    projectId: 'challenge-rickyflix',
    storageBucket: 'challenge-rickyflix.appspot.com',
    iosBundleId: 'com.example.rickyflixChallenge.RunnerTests',
  );
}
